// estilos globales
'use client'
import '../styles/globals.css'
import { SessionProvider } from "next-auth/react"
import App from '../components/App'


import { Navigation } from '../components/Navigation'
import { font } from './font'
import Providers from './Providers'

/* export const metadata = {
  title: 'UN titulo',
  description: 'Generated by Next.js'
} */

export default function RootLayout ({ children, session}) {
  return (
    
      <html lang='es'>
        <head />
        
        <body className={font.variable}>
        <SessionProvider session={session}>
          <Providers>
            <Navigation />

            <App children={children} />
            
          </Providers>
          </SessionProvider>
        </body>
        
        
      </html>
    
  )
}
