import { Navigation } from './components/Navigation'

export const metadata = {
  title: 'UN titulo',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
